databases:
  - name: SisPottery
    plan: free
    databaseName: SisPottery
    user: SisPottery

services:
  - type: web
    plan: free
    name: SisPottery
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SisPottery
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false