# development:
#   adapter: redis
#   url: redis://localhost:6379/1

# test:
#   adapter: test

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: sis_pottery_gallery_production

development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://redis-17107.c1.asia-northeast1-1.gce.cloud.redislabs.com:17107" } %>
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url: redis://default:GOWaY3mBVaVr2PWMisUmCxt67mmMCbIo@redis-17107.c1.asia-northeast1-1.gce.cloud.redislabs.com:17107
  channel_prefix: sis_pottery_gallery_production
  # url: redis://redis-17107.c1.asia-northeast1-1.gce.cloud.redislabs.com:17107



# 
  # url: redis://10.10.3.153:6381
